apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-storage-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kafka_data"